### ISSUE TITLE
Unable to apply changes to localhost due to sudo bug

### ISSUE THREAD

**Issue by tjbenator** [binarypenguin/automation#13]
Caused by Ansible issue: https://github.com/ansible/ansible/issues/13728

Work around is to connect to the local machine using ssh:
```hostname ansible_python_interpreter=/usr/bin/python2```

Packages are failing to install. Here is the section that is failing:
```
- name: Ensure packages are installed
  pacman: pkg={{item}} state=latest update_cache=yes
  with_items:
  - cowsay
  - fortune-mod
  - git
...
```
https://github.com/binarypenguin/automation/blob/alpha/roles/common/tasks/arch.yml

Error given.
```
fatal: [hostname]: FAILED! => {"failed": true, "msg": "ERROR! privilege output closed while waiting for password prompt:\nBECOME-SUCCESS-icxlorfbdaaxsvqlaamdcklnzmnxxdxu\n{\"msg\": \"package(s) already installed. \", \"invocation\": {\"module_args\": {\"upgrade\": false, \"force\": false, \"_ansible_no_log\": false, \"recurse\": false, \"_ansible_verbosity\": 1, \"state\": \"present\", \"update_cache\": false, \"pkg\": \"fortune-mod\", \"_ansible_debug\": false, \"_ansible_diff\": false, \"_ansible_check_mode\": false, \"name\": [\"fortune-mod\"]}}, \"changed\": false}\n"}
```
